version: "2"
networks:
  demo:
services:
  peer0.org0.com:
    container_name: peer0.org0.com
    image: hyperledger/fabric-peer:2.2.0
    environment:
      - CORE_PEER_ID=peer0.org0.com
      - CORE_PEER_ADDRESS=peer0.org0.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org0.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org0.com:10061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org0.com:10051
      - CORE_PEER_LOCALMSPID=Org0MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=multiorganization_demo
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:2.2.0
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - INFO_WARNING_LOGGABLE=true
      - ENV_ENABLE_HTTP=true
    ports:
      - "10051:10051"
      - "10052:10052"
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org0.com/peers/peer0.org0.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org0.com/peers/peer0.org0.com/tls:/etc/hyperledger/fabric/tls
    networks:
      demo:
