---
Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    AdminPrincipal: Role.ADMIN
    MSPDir: crypto-config/ordererOrganizations/demo.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &Org0
    Name: Org0MSP
    ID: Org0MSP
    AdminPrincipal: Role.ADMIN
    MSPDir: crypto-config/peerOrganizations/org0.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org0MSP.admin', 'Org0MSP.peer', 'Org0MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('Org0MSP.admin', 'Org0MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Org0MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org0MSP.peer')"
    AnchorPeers:
      - Host: peer0.org0.com
        Port: 10051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true

  Orderer: &OrdererCapabilities
    V2_0: true

  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"

  Capabilities:
    <<: *ApplicationCapabilities
Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.demo.com:5050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  OrdererSoloGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Org0

  #          - *Org3
  #
  #          - *Org4

  OrdererRaftGenesis:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: orderer.demo.com
            Port: 5050
            ClientTLSCert: crypto-config/ordererOrganizations/demo.com/orderers/orderer.demo.com/tls/server.crt
            ServerTLSCert: crypto-config/ordererOrganizations/demo.com/orderers/orderer.demo.com/tls/server.crt
      #                - Host: orderer3.demo.com
      #                  Port: 5053
      #                  ClientTLSCert: crypto-config/ordererOrganizations/demo.com/orderers/orderer3.demo.com/tls/server.crt
      #                  ServerTLSCert: crypto-config/ordererOrganizations/demo.com/orderers/orderer3.demo.com/tls/server.crt
      #                - Host: orderer4.demo.com
      #                  Port: 5054
      #                  ClientTLSCert: crypto-config/ordererOrganizations/demo.com/orderers/orderer4.demo.com/tls/server.crt
      #                  ServerTLSCert: crypto-config/ordererOrganizations/demo.com/orderers/orderer4.demo.com/tls/server.crt
      Addresses:
        - orderer.demo.com:5050
      #                - orderer3.demo.com:5053
      #                - orderer4.demo.com:5054
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - <<: *OrdererOrg
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Org0

  #          - *Org3
  #
  #          - *Org4

  DemoChannel0:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org0

      #        - *Org3
      #
      #        - *Org4

      Capabilities:
        <<: *ApplicationCapabilities

  DemoChannel1:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org0

      #        - *Org3
      #
      #        - *Org4

      Capabilities:
        <<: *ApplicationCapabilities
